!munch.Munch
missing_percent: .1
dataset: pancreas
work_dir: experiments/pancreas_missing/
batch_size: 16
model_name: ecg
nepoch: 10000
device: cuda:0
betas: 0.9, 0.999
early_stop: True
early_stop_patience: 100
epoch_interval_to_save: 1
epoch_interval_to_val: 1
latent_dim: 1024
load_model: null
loss: cd
lr: 0.0001
lr_clip: 1.0e-06
lr_decay: True
lr_decay_interval: 400
lr_decay_rate: 0.7
lr_step_decay_epochs: null
lr_step_decay_rates: null
manual_seed: null
num_coarse_points: 512
num_dense_points: 2048
num_input_points: 2048
optimizer: Adam
save_predictions: true
save_vis: true
start_epoch: 0
step_interval_to_print: 500
use_mean_feature: false
varying_constant: 0.01, 0.1, 0.5
varying_constant_epochs: 50, 200
weight_decay: 0
workers: 0